// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdgulehinkdtppxhxfat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZ3VsZWhpbmtkdHBweGh4ZmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTAwOTMsImV4cCI6MjA2NTU4NjA5M30.cQiijn1c7rblRB4CQ7CeuW07cGnEnLF6MbEh3uWqkwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);